name: GitHub Actions Demo
on: [push]
jobs:
  download-usercentrics:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          curl --location --request GET 'https://app.usercentrics.eu/browser-ui/2.43.0/bundle.js' 